# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Correlationc <- function(coordsx, coordsy, theta, matern, same) {
    .Call(`_spLMC_Correlationc`, coordsx, coordsy, theta, matern, same)
}

daggp_build <- function(coords, dag, phi, sigmasq, nu, tausq, matern = 1L, num_threads = 1L, prune_dag = FALSE) {
    .Call(`_spLMC_daggp_build`, coords, dag, phi, sigmasq, nu, tausq, matern, num_threads, prune_dag)
}

lmc_response <- function(Y, coords, custom_dag, theta_opts, A_start, mcmc = 1000L, print_every = 100L, dag_opts = 0L, upd_A = TRUE, upd_theta = TRUE, num_threads = 1L) {
    .Call(`_spLMC_lmc_response`, Y, coords, custom_dag, theta_opts, A_start, mcmc, print_every, dag_opts, upd_A, upd_theta, num_threads)
}

